.eslintrc.json, .github/workflows/ci.yml, README.md, package.json, src/styled.d.ts
=> build: add github ci

.github/workflows/deploy.yml
=> buuild: add github config

package.json, src/services/api/index.test.ts, src/services/api/index.ts, yarn.lock
=> feat: add service api

package.json, styles/styled.d.ts, yarn.lock
=> feat: add style config

public/locales/en/translation.json, src/config/routes/Navigation/styles.ts
- Adjust copy menu Dashboard > Treasure Dashboard
=> fix: adjust copy menu

src/config/routes/privateRoute.tsx, src/utils/constants.ts
- Updating token in private route
=> feat: add token in private route

package.json, src/hooks/apiHooks/usePersonPayments/index.ts, src/pages/PurchasesPage/PurchaseItems/index.tsx, src/pages/PurchasesPage/PurchaseItems/styles.ts, src/pages/PurchasesPage/PurchasesListSection/index.tsx, src/pages/PurchasesPage/PurchasesListSection/styles.ts, src/services/api/index.ts, src/services/api/personPaymentsApi/index.test.ts, src/services/api/personPaymentsApi/index.ts, yarn.lock
- Add pagination to PurchasesPage
=> feat: add react-paginate

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/PurchasesPage/PurchaseItems/index.tsx, src/pages/PurchasesPage/PurchasesListSection/index.test.tsx, src/pages/PurchasesPage/PurchasesListSection/index.tsx, src/pages/PurchasesPage/PurchasesListSection/styles.ts, src/types/entities/PersonPayment.ts
- Filter by email in purchases page
- Test A
=> Add filter by email to purchases page

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/PurchasesPage/PurchaseItems/index.tsx, src/pages/PurchasesPage/PurchasesListSection/index.tsx, src/types/entities/Guest.ts, src/types/entities/Person.ts
- Show wallet address when is crypto payment
- Adjust copy text and translation
- Add condition to show wallet address when is crypto payment
- closes [#TECH-156](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26/backlog?view=detail&selectedIssue=TECH-156&issueLimit=100)
- Go to purchase page and verify if when is crypto payment show a wallet address
=> (TECH-156) Show wallet address when is crypto payment

src/pages/DashboardPage/TreasureSection/CardTextGraph/index.tsx
=> fix: add guard to pool address

.husky/pre-commit, public/locales/en/translation.json, public/locales/pt/translation.json, src/components/moleculars/cards/Card/index.stories.tsx, src/components/moleculars/cards/Card/index.test.tsx, src/components/moleculars/cards/Card/index.tsx, src/components/moleculars/cards/Card/styles.ts, src/components/moleculars/cards/CardTextGraph/styles.ts, src/hooks/apiHooks/useApiIntegrations/index.test.ts, src/hooks/apiHooks/useApiIntegrations/index.ts, src/layouts/MainLayout/styles.ts, src/pages/DashboardPage/TreasureSection/CardTextGraph/styles.ts, src/pages/DashboardPage/TreasureSection/WalletCard/index.test.tsx, src/pages/DashboardPage/TreasureSection/WalletCard/index.tsx, src/pages/DashboardPage/TreasureSection/WalletCard/styles.ts, src/pages/DashboardPage/TreasureSection/index.tsx, src/pages/DashboardPage/TreasureSection/styles.ts, src/utils/constants.ts
- Added wallet information on dash page
- all integrations will have ribon's wallet, so i'm using Ribon Integration to get the wallet address
- Compare the info from the wallet with the dashboard
=> Tech 165: Wallet Information on dash page

src/hooks/apiHooks/useApiIntegrations/index.test.ts, src/hooks/apiHooks/useApiIntegrations/index.ts, src/hooks/apiHooks/useCauses/index.test.ts, src/hooks/apiHooks/useCauses/index.ts, src/lib/currentLanguage/index.ts, src/pages/integrations/IntegrationDetailsPage/index.tsx, src/pages/integrations/UpsertIntegrationPage/index.tsx, src/services/api/causesApi/index.test.ts, src/services/api/causesApi/index.ts, src/services/api/index.ts, src/services/api/integrationsApi/index.test.ts, src/services/api/integrationsApi/index.ts
- language on header for all api requests
- Test A
=> fix: language param for all api requests

public/locales/en/translation.json, public/locales/pt/translation.json, src/assets/icons/arrow-down-icon.svg, src/components/atomics/Dropdown/index.stories.tsx, src/components/atomics/Dropdown/index.test.tsx, src/components/atomics/Dropdown/index.tsx, src/components/atomics/Dropdown/styles.ts, src/components/moleculars/modals/ModalBlank/index.stories.tsx, src/components/moleculars/modals/ModalBlank/index.test.tsx, src/components/moleculars/modals/ModalBlank/index.tsx, src/components/moleculars/modals/ModalBlank/styles.ts, src/config/routes/index.tsx, src/config/testUtils/index.tsx, src/hooks/apiHooks/useNonProfits/index.test.ts, src/hooks/apiHooks/useNonProfits/index.ts, src/pages/NonProfitsPage/NonProfitItems/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.test.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/styles.ts, src/pages/NonProfitsPage/index.tsx, src/pages/NonProfitsPage/styles.ts, src/services/api/nonProfitsApi/index.ts, src/styles/typography/default.ts, src/types/apiResponses/nonProfit.ts, src/types/entities/NonProfit.ts, src/utils/constants.ts
- Adding creation and edition to Ngo.
- We still need to implement the details page. It'll be done in another PR.
=> Add creation and edition to Ngo

.husky/pre-commit, .stylelintrc.json, package.json, src/components/atomics/Buttons/ButtonSwitch/styles.ts, src/components/atomics/CopyableAddress/styles.ts, src/components/atomics/Tooltip/styles.ts, src/components/moleculars/FileUpload/styles.ts, src/components/moleculars/cards/Card/styles.ts, src/components/moleculars/cards/CardTextGraph/styles.ts, src/components/moleculars/modals/ModalImage/styles.ts, src/pages/DashboardPage/IntegrationsSection/styles.ts, src/pages/DashboardPage/TreasureSection/CardTextGraph/CauseCard/styles.ts, src/pages/DashboardPage/TreasureSection/CardTextGraph/styles.ts, src/pages/DashboardPage/TreasureSection/WalletCard/styles.ts, src/pages/DashboardPage/TreasureSection/styles.ts, src/pages/PurchasesPage/PurchasesListSection/styles.ts, src/pages/causes/CausesDetailsPage/styles.ts, yarn.lock
- changed stylelintrc file so --fix could work
- Test A
=> fix: stylelint --fix is working now

src/pages/NonProfitsPage/NonProfitItems/styles.ts, src/pages/PurchasesPage/PurchaseItems/styles.ts, src/pages/causes/CausesPage/CausesItems/styles.ts
- refund icon on purchase page
- Test A
=> Tech-175: Fix refund icon

src/pages/causes/CausesDetailsPage/index.tsx, src/pages/causes/CausesDetailsPage/styles.ts, src/types/entities/Cause.ts
- Add non profits link on cause details
- Put a card to link non profit on cause details
- closes [#TECH-158](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-158)
- Verify in projects links on cause details go to non profit page details
=> (TECH-158) Add non profits link on cause details

src/pages/integrations/IntegrationDetailsPage/index.tsx
- Remove integration balance of integration details because the balance is one for all them
- Remove balance card component 
- closes **[#TECH-196](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26/backlog?view=detail&selectedIssue=TECH-196&issueLimit=100)**
- Verify if card balance still in integration details
=> (TECH-196) Remove integration balance of integration details

.github/workflows/firebase-hosting-pull-request.yml
- Added new environment for staging 
- Test A
=> fix: new environment

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/PurchasesPage/PurchaseItems/index.tsx, src/pages/PurchasesPage/PurchasesListSection/index.tsx, src/types/entities/PersonPayment.ts
- Separate columns value and usdc
- See on purchase page if the columns value and usdc are correct
=> Tech 157: Purchase value adjust

public/locales/en/translation.json, public/locales/pt/translation.json
- Impact cost not displaying correctly
- Add USDC on translation
- eg: closes [#TECH-208](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-206)
=> (TECH-206) - Impact cost not displaying correctly

src/pages/DashboardPage/TreasureSection/CardTextGraph/index.tsx, src/pages/DashboardPage/TreasureSection/index.tsx, src/pages/causes/CausesPage/CausesItems/index.tsx
- Adjust balance value of donation pool
- Format balance value to 6 decimals
- eg: closes [#TECH-193](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-193)
=> (TECH-193) Adjust balance value of donation pool

src/config/networks/index.ts, src/pages/DashboardPage/TreasureSection/CardTextGraph/index.stories.tsx, src/pages/DashboardPage/TreasureSection/CardTextGraph/index.tsx, src/pages/DashboardPage/TreasureSection/index.test.tsx, src/pages/DashboardPage/TreasureSection/index.tsx
- thegraph api is returning wrong values for balance, so this fix is for take this data from the library instead of from thegraph api
- Test A
=> fix: dashboard infos

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/integrations/IntegrationDetailsPage/index.test.tsx, src/pages/integrations/IntegrationDetailsPage/index.tsx, src/pages/integrations/IntegrationsPage/IntegrationsListSection/index.test.tsx, src/pages/integrations/IntegrationsPage/IntegrationsListSection/index.tsx
- Add link to integration dashboard on integration details and integrations list
- Add translate
- Add field integration dashboard address on list of integrations and details of integration
- eg: closes [#DAPP-624](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-624)
- Verify if has the field integration dashboard address on integrations list and details of integration
=> (DAPP-624) Add link to integration dashboard

src/components/atomics/Buttons/ButtonSwitch/index.stories.tsx, src/components/atomics/Dropdown/index.stories.tsx, src/pages/DashboardPage/TreasureSection/WalletCard/index.tsx
- The conversion was wrong
- Test A
=> fix: integration wallet dashboard

src/pages/DashboardPage/TreasureSection/CardTextGraph/index.tsx
- render graph after get pools balance
- Test A
=> fix: render graph after get pools balance

src/config/networks/index.ts, src/pages/DashboardPage/TreasureSection/WalletCard/index.tsx
- added integration holding wallet so we can monitor the matic and the donation limit
- Test A
=> Tech 282: fix dashboard integration card

src/hooks/apiHooks/useNonProfits/index.ts, src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/StoriesForm/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx, src/types/apiResponses/nonProfit.ts, src/types/entities/NonProfit.ts
- Fix edit/create non profits 
- Test A
=> TECH 260 edit/create non profits

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/NonProfitsDetailsPage/styles.ts
- Add details of impacts on non profits details page
=> feat: add impacts on non profits details page

.stylelintrc.json, src/components/atomics/Buttons/ButtonSwitch/styles.ts, src/components/moleculars/FileUpload/styles.ts, src/components/moleculars/cards/Card/styles.ts, src/components/moleculars/cards/CardTextGraph/styles.ts, src/pages/DashboardPage/TreasureSection/CardTextGraph/styles.ts, src/pages/DashboardPage/TreasureSection/WalletCard/styles.ts, src/pages/NonProfitsPage/NonProfitsDetailsPage/styles.ts, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactForm/styles.ts, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactPreviewer/styles.ts, src/pages/causes/CausesDetailsPage/styles.ts, src/styles/globalStyle.ts, src/styles/typography/default.ts, src/styles/typography/stylized.ts, src/styles/typography/typography.ts
=> Tech 280: new typography

src/pages/PurchasesPage/PurchaseItems/index.tsx, src/pages/PurchasesPage/PurchasesListSection/index.tsx
- The refund modal was not closing 
- Test A
=> fix: bug modal refund

src/pages/LoginPage/index.tsx
- Fix login with google
- Test A
=> fix: login with google

src/services/api/articlesApi/index.test.ts, src/services/api/articlesApi/index.ts
-show hidden articles in articles list page
=> fix: show hidden articles in articles list page

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/news/UpsertArticleNewsPage/index.tsx
=> fix: remove required from link input

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/news/NewsDetailsPage/index.tsx, src/pages/news/NewsPage/NewsItems/index.tsx, src/pages/offers/UpsertOfferPage/index.tsx, src/types/entities/Article.ts, src/types/entities/Offer.ts
- Add subscription when add new offer
- eg: closes [#DAPP-733](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-733)
=> fix: add subscription when add new offer

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/news/NewsDetailsPage/index.test.tsx, src/pages/news/NewsDetailsPage/index.tsx, src/pages/news/NewsPage/NewsItems/index.tsx, src/pages/news/NewsPage/NewsListSection/index.test.tsx, src/pages/news/NewsPage/NewsListSection/index.tsx, src/pages/news/UpsertArticleNewsPage/index.tsx, src/pages/news/UpsertArticleNewsPage/styles.ts, src/pages/offers/UpsertOfferPage/index.tsx, src/types/apiResponses/article.ts, src/types/entities/Article.ts
- add field language to news adjust list of news and details
- eg: closes [#DAPP-737](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-737)
- Test A
=> feat: add field language to news

src/pages/PurchasesPage/PurchaseItems/index.tsx, src/types/entities/CryptoUser.ts, src/types/entities/PersonPayment.ts
- Refactors purchase page so we can get payer id directly from the back end's response
- check on purchase page if the user id column shows the user's email if the user has donated by credit card and the wallet if they donated by crypto currency
=> refactor: references payer id on purchases page

src/pages/integrations/IntegrationDetailsPage/index.tsx
- page is broken
- remove unnecessary code
- Test A
=> fix: Integration Details Page

public/locales/en/translation.json, public/locales/pt/translation.json
=> chore: adjust translate

src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactForm/index.tsx
- remove require end date on non profit impacts
=> fix: remove required end date

public/locales/en/translation.json, public/locales/pt/translation.json, src/components/moleculars/infoName/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactForm/index.tsx
- add condition to infoname to show a tag if is optional or not
=> feat: add condition to infoname to show if is optional or not

src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactForm/index.tsx
=> fix: add required to end date

src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactForm/index.tsx
=> fix: end date

src/hooks/useContract/index.ts
=> fix: contract signer

src/pages/bigDonors/CreateBigDonationsPage/index.tsx, src/types/apiResponses/BigDonation.ts
- Add feeable param to createBigDonation
- Test A
=> feat: add feeable param to createBigDonation

src/services/api/personPaymentsApi/index.ts
- the create big donation route was wrong
- Test A
=> fix: create big donation route 

package.json, public/locales/en/translation.json, public/locales/pt/translation.json, src/hooks/apiHooks/useUploadFile/index.ts, src/pages/NonProfitsPage/UpsertNonProfitPage/StoriesForm/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx, src/pages/causes/UpsertCausePage/index.tsx, src/pages/causes/UpsertCausePage/styles.ts, src/types/apiResponses/cause.ts, src/types/apiResponses/nonProfit.ts, src/types/apiResponses/story.ts, src/types/entities/Cause.ts, src/types/entities/NonProfit.ts, src/types/entities/Story.ts, yarn.lock
- alt fields to nonprofits and causes
- Test A
=> feat: alt fields to nonprofits and causes

package.json, public/locales/en/translation.json, public/locales/pt/translation.json, src/App.tsx, src/config/testUtils/renders.tsx, src/contexts/authenticationContext/index.tsx, src/pages/DashboardPage/index.tsx, src/pages/LoginPage/PasswordLoginSection/index.tsx, src/pages/LoginPage/index.test.tsx, src/pages/LoginPage/index.tsx, src/pages/LoginPage/styles.ts, src/services/api/index.ts, src/services/api/userManagerApi/index.ts, src/utils/constants.ts, yarn.lock
- Add refresh token logic
- Check the "token" key attribute in application cookies of the browser
- Logout and login again and check if it changed
- Check if you are able to make the requests in both uses
=> feat: add refresh token logic to api

src/types/enums/Gateways.ts
Add stripe global as an offer gateway option
=> feat: stripe global on upsert offers

src/pages/offers/UpsertOfferPage/index.tsx
=> fix: replace space with underscore

src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx
- it's no possible to update a nonprofit without removing those image url
- Test A
=> fix: upsert non profit confirmation image

.github/workflows/deploy.yml
changes flow from develop to staging
=> fix: changes flow from develop to staging

public/locales/en/translation.json, public/locales/pt/translation.json, src/hooks/apiHooks/useCauses/index.test.ts, src/pages/causes/CausesDetailsPage/index.tsx, src/pages/causes/CausesPage/CausesItems/index.tsx, src/pages/causes/CausesPage/CausesListSection/index.tsx, src/pages/causes/UpsertCausePage/index.tsx, src/pages/causes/UpsertCausePage/styles.ts, src/services/api/causesApi/index.test.ts, src/types/apiResponses/cause.ts, src/types/entities/Cause.ts
- add checkbox to active and inactive a cause and put status on details and list
=> feat: add checkbox to active and inactive a cause

src/hooks/apiHooks/useArticles/index.ts, src/pages/news/NewsPage/NewsListSection/index.tsx
- shows 100 articles
- check checkbox pt and en on load
- Test A
=> fix: 100 articles

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/bigDonors/BigDonorsPage/BigDonorsItems/index.tsx, src/pages/bigDonors/BigDonorsPage/BigDonorsListSection/index.tsx, src/types/entities/BigDonor.ts
- Add link to big donors dashboard
- Test A
=> feat: add link to patrons dashboard

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/integrations/IntegrationDetailsPage/index.tsx, src/pages/integrations/IntegrationsPage/IntegrationsListSection/index.tsx, src/pages/integrations/IntegrationsPage/IntegrationsListSection/styles.ts, src/types/entities/Integration.ts
- Added integration deeplink address
- Test A
=> feat: integration deeplink address

package.json, public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactPreviewer/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactPreviewer/styles.ts, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx, yarn.lock
- Add preview of ticket impact 
- eg: closes [#PROD3-179](https://ribon.atlassian.net/jira/software/c/projects/PROD3/boards/28?modal=detail&selectedIssue=PROD3-179)
- Verify in upsert page of non profits if preview impacts change in real time
=> [PROD3-179] Preview of ticket impact

src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactPreviewer/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx
- impact previewer with real time update
- Test A
=> fix: impact previewer with real time update

src/pages/causes/UpsertCausePage/index.tsx
- Removes required from the description and adjusts name length 
- No
- [x ] Chore (change that does not effect how the code works, eg: change color)
=> fix: upsert cause

public/locales/en/translation.json, public/locales/pt/translation.json, src/hooks/apiHooks/useImpressionCards/index.test.ts, src/pages/impressionCards/ImpressionCardsPage/ImpressionCardsListSection/index.tsx, src/pages/impressionCards/UpsertImpressionCardPage/index.tsx, src/pages/impressionCards/UpsertImpressionCardPage/styles.ts, src/services/api/impressionCardsApi/index.test.tsx, src/types/entities/ImpressionCard.ts
- Add status and activity fields for the ImpressionCard entity
=> feat: client and activity fields

public/locales/en/translation.json, public/locales/pt/translation.json, src/hooks/apiHooks/useRibonConfig/index.test.ts, src/lib/centsFormatter/index.test.ts, src/lib/centsFormatter/index.ts, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactPreviewer/index.tsx, src/pages/SettingsPage/EditSettingsPage/index.tsx, src/pages/SettingsPage/EditSettingsPage/styles.ts, src/pages/SettingsPage/index.tsx, src/services/api/ribonConfigApi/index.test.ts, src/types/entities/RibonConfig.ts
- allow default ticket value to be a decimal
- Test A
=> fix: ribon config default ticket value

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/offers/OffersPage/OffersItems/index.tsx, src/pages/offers/OffersPage/OffersListSection/index.tsx, src/pages/offers/UpsertOfferPage/index.tsx, src/pages/offers/offerDetailsPage/index.tsx, src/types/entities/Offer.ts
- added category to offers
- Test A
=> feat: added category to offers

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/offers/OffersPage/OffersItems/index.tsx, src/pages/offers/OffersPage/OffersListSection/index.tsx, src/pages/offers/UpsertOfferPage/index.tsx, src/pages/offers/UpsertOfferPage/styles.ts, src/pages/offers/offerDetailsPage/index.tsx, src/types/entities/Offer.ts, src/types/entities/Plan.ts
- Upsert Plans through offers
- Test A
=> Prod3 399: Upsert Plans through offers

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/SettingsPage/EditSettingsPage/index.tsx, src/pages/SettingsPage/index.tsx, src/types/entities/RibonConfig.ts
- adds ribonClubFeePercentage to settings page
- [#prod3-454](https://ribon.atlassian.net/browse/PROD3-454?atlOrigin=eyJpIjoiODY5ZDc4MWE4ZGQ3NDg1ZThlNjIxODBhZWY2NTVkZTYiLCJwIjoiaiJ9)
Go to settings page and try to edit and save ribonClubFeePercentage
=> feat: adds ribonClubFeePercentage

src/pages/offers/UpsertOfferPage/index.tsx, src/types/entities/Offer.ts
- remove plansAttributes if direct_contribution
- Test A
=> fix: upsert offer

src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactPreviewer/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx
- round minimum number of tickets
- Test A
=> fix: round minimum number of tickets

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/ImpactForm/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx
=> fix: lint from Pedro's PR

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx, src/types/apiResponses/nonProfit.ts, src/types/entities/NonProfit.ts
- Add icon input and details view to ngos;
-
=> feat: add icon to non profit pages [PROD3-582]

package.json, public/locales/en/translation.json, public/locales/pt/translation.json, src/App.test.tsx, src/components/moleculars/Markdown/Editor/index.tsx, src/components/moleculars/Markdown/Editor/styles.ts, src/components/moleculars/Markdown/Viewer/index.tsx, src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/StoriesCard/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/StoriesForm/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/StoriesForm/styles.ts, src/pages/NonProfitsPage/UpsertNonProfitPage/index.test.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx, yarn.lock
- This PR add a markdown to the NGO form.
- The lib installed do no support to sourcemaps for this projects because originated with CRA (create react app). When run project you are receipt warnings; to bypass, necessary set in ".env" that variable: GENERATE_SOURCEMAP=false.
The project github with issues related up above:
(https://github.com/uiwjs/react-md-editor/issues/624#issuecomment-2005778443)
Open project manager and add new or edit a NGOs with new markdown editor;
=> Feat/Add markdown editor [PROD3-591]

public/locales/en/translation.json, public/locales/pt/translation.json, src/hooks/apiHooks/useApiIntegrations/index.ts, src/pages/integrations/UpsertIntegrationPage/index.tsx, src/types/entities/Integration.ts
=> feat: new integration fields

public/locales/en/translation.json, public/locales/pt/translation.json, src/config/routes/Navigation/index.tsx, src/config/routes/index.tsx, src/hooks/apiHooks/useWarmglowMessages/index.test.ts, src/hooks/apiHooks/useWarmglowMessages/index.ts, src/pages/tags/UpsertTagPage/index.tsx, src/pages/warmglowMessages/UpsertWarmglowMessagePage/index.tsx, src/pages/warmglowMessages/UpsertWarmglowMessagePage/styles.ts, src/pages/warmglowMessages/WarmglowMessageDetailsPage/index.test.tsx, src/pages/warmglowMessages/WarmglowMessageDetailsPage/index.tsx, src/pages/warmglowMessages/WarmglowMessageDetailsPage/styles.ts, src/pages/warmglowMessages/WarmglowMessagesPage/WarmglowMessagesItems/index.tsx, src/pages/warmglowMessages/WarmglowMessagesPage/WarmglowMessagesItems/styles.ts, src/pages/warmglowMessages/WarmglowMessagesPage/WarmglowMessagesListSection/index.test.tsx, src/pages/warmglowMessages/WarmglowMessagesPage/WarmglowMessagesListSection/index.tsx, src/pages/warmglowMessages/WarmglowMessagesPage/WarmglowMessagesListSection/styles.ts, src/pages/warmglowMessages/WarmglowMessagesPage/index.test.tsx, src/pages/warmglowMessages/WarmglowMessagesPage/index.tsx, src/pages/warmglowMessages/WarmglowMessagesPage/styles.ts, src/services/api/warmglowMessagesApi/index.test.ts, src/services/api/warmglowMessagesApi/index.ts, src/types/entities/WarmglowMessage.ts
I can't think any translation to warmglow so...
- Upsert message warmglow
- List and details " "
- Tests
- eg: closes [#PROD3-621]()
- Create a warmglow message
- Edit a warmglow message
- List all " " 
- See details of a warmglow message
=> [PROD3-621] List, details and upsert warmglow message

public/locales/en/translation.json, public/locales/pt/translation.json, src/pages/NonProfitsPage/NonProfitsDetailsPage/index.tsx, src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx
- Adjust the recommended size for confirmation image;
- shows confirmation image on non profit details page
- No.
=> fix: confirmation image

src/pages/integrations/UpsertIntegrationPage/index.tsx
=> fix: remove requried clause for some fields

src/pages/offers/UpsertOfferPage/index.tsx
- Add category business to offer 
- eg: closes [#PROD3-687]()
- Adjust a category of some offer
=> [PROD3-687] Add category business to offer 

src/pages/NonProfitsPage/UpsertNonProfitPage/index.tsx
=> fix: adjust non profit name length
